timeout: 5
default_entry: 1

/Ubuntu Linux
    protocol: linux
    kernel_path: boot():/vmlinuz-{KERNEL_VERSION}-generic
    module_path: boot():/initrd.img-{INITRD_VERSION}-generic
    cmdline: root=/dev/mapper/root rootflags=subvol=@ rd.luks.name={LUKS_UUID}=root rd.luks.options=discard cryptdevice={LUKS_UUID}:root:allow-discards rootfstype=btrfs quiet splash loglevel=3